# some versions are in shared-versions.properties
[versions]
ant = "1.10.15!!"
# Don't forget to bump versions in
# platforms/core-runtime/base-asm/src/main/java/org/gradle/model/internal/asm/AsmConstants.java
# when upgrading ASM.
asm = "9.9!!"
awsS3 = "1.12.780!!"
bouncycastle = "1.81!!"
commonsCodec = "1.18.0!!"
commonsCompress = "1.26.1!!"
commonsHttpclient = "4.5.14!!"
commonsIo = "2.15.1!!"
commonsLang = "3.20.0!!"
configurationCacheReport = "1.32!!"
fastutil = "8.5.2!!"
gcs = "v1-rev20220705-1.32.1!!"
googleApiClient = "1.34.0!!" # our GCS version requires 1.34.0
googleHttpClient = "1.42.2!!" # Covers googleHttpClient, googleHttpClientGson, googleHttpClientApacheV2, our Google API Client version requires it
googleOauthClient = "1.34.1!!" # our Google API Client version requires 1.34.1
gradleFileEvents = "0.2.8!!"
gson = "2.13.1!!"
guava = "33.4.6-jre"
httpcore = "4.4.14!!"
inject = "1!!"
ivy = "2.5.3!!"
jansi = "2.4.2!!" # If JANSI is updated run on a Windows terminal CMD.EXE to make sure the ansi control characters are not messing up the output
jatl = "0.2.3!!"
javaParser = "3.27.1!!"
javaPoet = "1.13.0!!"
jcifs = "1.3.17!!"
jetbrainsAnnotations = "24.0.1!!"
jgit = "7.2.1.202505142326-r!!"
jna = "5.17.0!!"
jnr = "0.10.4!!"
joda = "2.14.0!!"
jquery = "3.7.1!!" # used in resoures
jsch = "0.2.16!!"
jsoup = "1.15.3!!"
jspecify = "1.0.0!!"
jsr305 = "3.0.2!!"
kotlin = "2.3.0!!"
kotlinxSerialization = "1.9.0!!"
kryo = "2.24.0!!"
minlog = "1.2!!"
nativePlatform = "0.22-milestone-29!!"
objenesis = "2.6!!" # transitive dependency of kryo
plexusCipher = "2.0!!"
plexusInterpolation = "1.26!!"
plexusSecDispatcher = "2.0!!"
plexusUtils = "3.5.1!!"
plist = "1.27!!"
slf4j = "2.0.17!!"
snakeyaml = "2.0!!"
sshd = "2.15.0!!"
tomlj = "1.0.0!!"

[libraries]
ant = { group = "org.apache.ant", name = "ant", version.ref = "ant" }
antLauncher = { group = "org.apache.ant", name = "ant-launcher", version.ref = "ant" }
asm = { group = "org.ow2.asm", name = "asm", version.ref = "asm" }
asmCommons = { group = "org.ow2.asm", name = "asm-commons", version.ref = "asm" }
asmTree = { group = "org.ow2.asm", name = "asm-tree", version.ref = "asm" }
asmUtil = { group = "org.ow2.asm", name = "asm-util", version.ref = "asm" }
awsS3Core = { group = "com.amazonaws", name = "aws-java-sdk-core", version.ref = "awsS3" }
awsS3Kms = { group = "com.amazonaws", name = "aws-java-sdk-kms", version.ref = "awsS3" }
awsS3S3 = { group = "com.amazonaws", name = "aws-java-sdk-s3", version.ref = "awsS3" }
awsS3Sts = { group = "com.amazonaws", name = "aws-java-sdk-sts", version.ref = "awsS3" }
bouncycastlePgp = { group = "org.bouncycastle", name = "bcpg-jdk18on", version.ref = "bouncycastle" }
bouncycastleProvider = { group = "org.bouncycastle", name = "bcprov-jdk18on", version.ref = "bouncycastle" }
commonsCodec = { group = "commons-codec", name = "commons-codec", version.ref = "commonsCodec" }
commonsCompress = { group = "org.apache.commons", name = "commons-compress", version.ref = "commonsCompress" }
commonsHttpclient = { group = "org.apache.httpcomponents", name = "httpclient", version.ref = "commonsHttpclient" }
commonsIo = { group = "commons-io", name = "commons-io", version.ref = "commonsIo" }
commonsLang = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commonsLang" }
configurationCacheReport = { group = "org.gradle.buildtool.internal", name = "configuration-cache-report", version.ref = "configurationCacheReport" }
errorProneAnnotations = { group = "com.google.errorprone", name = "error_prone_annotations", version.ref = "errorProne" }
fastutil = { group = "it.unimi.dsi", name = "fastutil", version.ref = "fastutil" }
gcs = { group = "com.google.apis", name = "google-api-services-storage", version.ref = "gcs" }
googleApiClient = { group = "com.google.api-client", name = "google-api-client", version.ref = "googleApiClient" }
googleHttpClient = { group = "com.google.http-client", name = "google-http-client", version.ref = "googleHttpClient" }
googleHttpClientApacheV2 = { group = "com.google.http-client", name = "google-http-client-apache-v2", version.ref = "googleHttpClient" }
googleHttpClientGson = { group = "com.google.http-client", name = "google-http-client-gson", version.ref = "googleHttpClient" }
googleOauthClient = { group = "com.google.oauth-client", name = "google-oauth-client", version.ref = "googleOauthClient" }
gradleFileEvents = { group = "org.gradle.fileevents", name = "gradle-fileevents", version.ref = "gradleFileEvents" }
groovy = { group = "org.apache.groovy", name = "groovy", version.ref = "groovy" } # Assuming Groovy 3 group
groovyAnt = { group = "org.apache.groovy", name = "groovy-ant", version.ref = "groovy" }
groovyAstbuilder = { group = "org.apache.groovy", name = "groovy-astbuilder", version.ref = "groovy" }
groovyDateUtil = { group = "org.apache.groovy", name = "groovy-dateutil", version.ref = "groovy" }
groovyDatetime = { group = "org.apache.groovy", name = "groovy-datetime", version.ref = "groovy" }
groovyDoc = { group = "org.apache.groovy", name = "groovy-groovydoc", version.ref = "groovy" }
groovyJson = { group = "org.apache.groovy", name = "groovy-json", version.ref = "groovy" }
groovyNio = { group = "org.apache.groovy", name = "groovy-nio", version.ref = "groovy" }
groovyTemplates = { group = "org.apache.groovy", name = "groovy-templates", version.ref = "groovy" }
groovyXml = { group = "org.apache.groovy", name = "groovy-xml", version.ref = "groovy" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
httpcore = { group = "org.apache.httpcomponents", name = "httpcore", version.ref = "httpcore" }
inject = { group = "javax.inject", name = "javax.inject", version.ref = "inject" }
ivy = { group = "org.apache.ivy", name = "ivy", version.ref = "ivy" }
jacksonAnnotations = { group = "com.fasterxml.jackson.core", name = "jackson-annotations", version.ref = "jackson" }
jacksonCore = { group = "com.fasterxml.jackson.core", name = "jackson-core", version.ref = "jackson" }
jacksonDatabind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
jacksonDatatypeJdk8 = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jdk8", version.ref = "jackson" }
jacksonDatatypeJsr310 = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310", version.ref = "jackson" }
jansi = { group = "org.fusesource.jansi", name = "jansi", version.ref = "jansi" }
jatl = { group = "com.googlecode.jatl", name = "jatl", version.ref = "jatl" }
javaParser = { group = "com.github.javaparser", name = "javaparser-core", version.ref = "javaParser" }
javaPoet = { group = "com.squareup", name = "javapoet", version.ref = "javaPoet" }
jcifs = { group = "jcifs", name = "jcifs", version.ref = "jcifs" }
jclToSlf4j = { group = "org.slf4j", name = "jcl-over-slf4j", version.ref = "slf4j" }
jetbrainsAnnotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrainsAnnotations" }
jgit = { group = "org.eclipse.jgit", name = "org.eclipse.jgit", version.ref = "jgit" }
jgitSsh = { group = "org.eclipse.jgit", name = "org.eclipse.jgit.ssh.apache", version.ref = "jgit" }
jgitSshAgent = { group = "org.eclipse.jgit", name = "org.eclipse.jgit.ssh.apache.agent", version.ref = "jgit" }
jna = { group = "net.java.dev.jna", name = "jna", version.ref = "jna" }
jnaPlatform = { group = "net.java.dev.jna", name = "jna-platform", version.ref = "jna" }
jnrConstants = { group = "com.github.jnr", name = "jnr-constants", version.ref = "jnr" }
joda = { group = "joda-time", name = "joda-time", version.ref = "joda" }
jquery = { group = "jquery", name = "jquery.min", version.ref = "jquery" }
jsch = { group = "com.github.mwiede", name = "jsch", version.ref = "jsch" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
jspecify = { group = "org.jspecify", name = "jspecify", version.ref = "jspecify" }
jsr305 = { group = "com.google.code.findbugs", name = "jsr305", version.ref = "jsr305" }
julToSlf4j = { group = "org.slf4j", name = "jul-to-slf4j", version.ref = "slf4j" }
kotlinAssignment = { group = "org.jetbrains.kotlin", name = "kotlin-assignment", version.ref = "kotlin" }
kotlinAssignmentCompilerEmbeddable = { group = "org.jetbrains.kotlin", name = "kotlin-assignment-compiler-plugin-embeddable", version.ref = "kotlin" }
kotlinBuildToolsImpl = { group = "org.jetbrains.kotlin", name = "kotlin-build-tools-impl", version.ref = "kotlin" }
kotlinCompilerEmbeddable = { group = "org.jetbrains.kotlin", name = "kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlinGradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinGradlePluginApi = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin-api", version.ref = "kotlin" }
kotlinJvmAbiGenEmbeddable = { group = "org.jetbrains.kotlin", name = "jvm-abi-gen-embeddable", version.ref = "kotlin" }
kotlinMetadataJvm = { group = "org.jetbrains.kotlin", name = "kotlin-metadata-jvm", version.ref = "kotlin" }
kotlinReflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
kotlinSamWithReceiver = { group = "org.jetbrains.kotlin", name = "kotlin-sam-with-receiver", version.ref = "kotlin" }
kotlinSamWithReceiverCompilerPlugin = { group = "org.jetbrains.kotlin", name = "kotlin-sam-with-receiver-compiler-plugin", version.ref = "kotlin" }
kotlinScriptRuntime = { group = "org.jetbrains.kotlin", name = "kotlin-script-runtime", version.ref = "kotlin" }
kotlinScriptingCommon = { group = "org.jetbrains.kotlin", name = "kotlin-scripting-common", version.ref = "kotlin" }
kotlinScriptingCompilerEmbeddable = { group = "org.jetbrains.kotlin", name = "kotlin-scripting-compiler-embeddable", version.ref = "kotlin" }
kotlinScriptingCompilerImplEmbeddable = { group = "org.jetbrains.kotlin", name = "kotlin-scripting-compiler-impl-embeddable", version.ref = "kotlin" }
kotlinScriptingJvm = { group = "org.jetbrains.kotlin", name = "kotlin-scripting-jvm", version.ref = "kotlin" }
kotlinScriptingJvmHost = { group = "org.jetbrains.kotlin", name = "kotlin-scripting-jvm-host", version.ref = "kotlin" }
kotlinStdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlinxCoroutinesJvm = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core-jvm", version.ref = "kotlinCoroutines" }
kotlinxSerializationCore = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinxSerialization" }
kotlinxSerializationJson = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kryo = { group = "com.esotericsoftware.kryo", name = "kryo", version.ref = "kryo" }
log4jToSlf4j = { group = "org.slf4j", name = "log4j-over-slf4j", version.ref = "slf4j" }
maven3Model = { group = "org.apache.maven", name = "maven-model", version.ref = "maven" }
maven3RepositoryMetadata = { group = "org.apache.maven", name = "maven-repository-metadata", version.ref = "maven" }
maven3Settings = { group = "org.apache.maven", name = "maven-settings", version.ref = "maven" }
maven3SettingsBuilder = { group = "org.apache.maven", name = "maven-settings-builder", version.ref = "maven" }
minlog = { group = "com.esotericsoftware.minlog", name = "minlog", version.ref = "minlog" }
nativePlatform = { group = "net.rubygrapefruit", name = "native-platform", version.ref = "nativePlatform" }
objenesis = { group = "org.objenesis", name = "objenesis", version.ref = "objenesis" }
plexusCipher = { group = "org.sonatype.plexus", name = "plexus-cipher", version.ref = "plexusCipher" }
plexusInterpolation = { group = "org.codehaus.plexus", name = "plexus-interpolation", version.ref = "plexusInterpolation" }
plexusSecDispatcher = { group = "org.codehaus.plexus", name = "plexus-sec-dispatcher", version.ref = "plexusSecDispatcher" }
plexusUtils = { group = "org.codehaus.plexus", name = "plexus-utils", version.ref = "plexusUtils" }
plist = { group = "com.googlecode.plist", name = "dd-plist", version.ref = "plist" }
slf4jApi = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
snakeyaml = { group = "org.yaml", name = "snakeyaml", version.ref = "snakeyaml" }
sshdCore = { group = "org.apache.sshd", name = "sshd-core", version.ref = "sshd" }
sshdOsgi = { group = "org.apache.sshd", name = "sshd-osgi", version.ref = "sshd" } # It contains sshd-core and sshd-common classes
sshdScp = { group = "org.apache.sshd", name = "sshd-scp", version.ref = "sshd" }
sshdSftp = { group = "org.apache.sshd", name = "sshd-sftp", version.ref = "sshd" }
tomlj = { group = "org.tomlj", name = "tomlj", version.ref = "tomlj" }
