[dependencies]
my-lib = "com.mycompany:mylib:1.4"
my-other-lib = { module = "com.mycompany:other", version="1.4" }
my-other-lib2 = { group = "com.mycompany", name="alternate", version="1.4" }
mylib-full-format = { group = "com.mycompany", name="alternate", version={ require = "1.4" } }
