name: Markdown Links ðŸ”—
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  check-links:
    name: Check ðŸ“
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository ðŸ“¥
        uses: actions/checkout@v6
      - name: Check links ðŸ”
        uses: lycheeverse/lychee-action@v2.7.0
        with:
          args: >
            --no-progress --offline '**/*.md' --include-fragments
            --exclude-path 'platforms/documentation/docs/src/docs/release/notes.md'
            --exclude-path 'platforms/documentation/docs/src/docs/release/notes-template.md'
            --exclude-path 'platforms/documentation/docs/src/docs/kotlin/Module.md'
          fail: true
