name: Markdown Links Check ðŸ”—
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
permissions: {}
jobs:
  check-links:
    name: Check Links ðŸ“
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ“¥
        uses: actions/checkout@v6
      - name: Check links ðŸ”
        uses: lycheeverse/lychee-action@v2.7.0
        with:
          # Excluded:
          # - notes.md and notes-template.md - because they are a part of user guide
          # - Kotlin's Module.md - because it's a part of the Kotlin DSL docs
          args: >
            --no-progress --offline '**/*.md' --include-fragments
            --exclude-path 'platforms/documentation/docs/src/docs/release/notes.md'
            --exclude-path 'platforms/documentation/docs/src/docs/release/notes-template.md'
            --exclude-path 'platforms/documentation/docs/src/docs/kotlin/Module.md'
          fail: true
