name: IDE Experience team notifier
run-name: Notify the IDE Experience team about relevant issues
on:
  issues:
    types:
      - labeled

jobs:
  send-slack-notification:
    if: ${{ github.event.label.name == 'in:ide' || github.event.label.name == 'in:eclipse-plugin' || github.event.label.name == 'in:idea-plugin' || github.event.label.name == 'in:tooling-api' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification about issues with specific labels
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "<https://github.com/gradle/gradle/${{ github.event.issue.number }}|[gradle/gradle#${{ github.event.issue.number }}]> `${{ github.event.issue.title }}` has label `${{ github.event.label.name }}`",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<https://github.com/gradle/gradle/${{ github.event.issue.number }}|[gradle/gradle#${{ github.event.issue.number }}]> `${{ github.event.issue.title }}` has label `${{ github.event.label.name }}`"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.IDE_EXPERIENCE_SLACK_WEBHOOK_URL }}